services:
  backend_test:
    container_name: bibliotecadebolso_backend_test
    env_file: .env
    build: ./app
    ports:
      - ${API_LOCAL_PORT}:${API_LOCAL_PORT}
    environment:
      DATABASE_URL: "postgres://bibliotecadebolso_test:123456789@database_test:5432/bibliotecadebolso_test?schema=bibliotecadebolso"
      NODE_ENV: test
      DB_HOST_DEV: database_test
      DB_NAME_DEV: bibliotecadebolso
      DB_USER_DEV: bibliotecadebolso
      DB_PORT_DEV: 5432
      DB_PASS_DEV: 123456789
      WAIT_HOSTS: database_test:5432
      WAIT_TIMEOUT: 600
      WAIT_SLEEP_INTERVAL: 10
    depends_on:
      - database_test
    command: >
      sh -c "
        /wait &&
        npx prisma generate --schema src/prisma/schema.prisma &&
        npx prisma db push --schema src/prisma/schema.prisma  &&
        npm run test-coverage"
    volumes:
      - ./app/coverage:/usr/src/app/coverage
  database_test:
    container_name: bibliotecadebolso_database_test
    image: postgres
    env_file: .env
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456789
      POSTGRES_USER: bibliotecadebolso_test
      POSTGRES_DATABASE: bibliotecadebolso_test
