name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  API_LOCAL_PORT: ${{ secrets.API_LOCAL_PORT }}
  JWT_TOKEN_SECRET: ${{ secrets.JWT_TOKEN_SECRET }}
  PRODUCTION_URL: ${{ secrets.PRODUCTION_URL }}
  CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
  GOOGLE_BOOKS_API: ${{ secrets.GOOGLE_BOOKS_API }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  SEND_GRID_API: ${{ secrets.SEND_GRID_API }}
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: bibliotecadebolso

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Create env file
        run: |
          touch .env
          echo API_LOCAL_PORT=${{ secrets.API_LOCAL_PORT }} >> .env
          echo JWT_TOKEN_SECRET=${{ secrets.JWT_TOKEN_SECRET }} >> .env
          echo PRODUCTION_URL=${{ secrets.PRODUCTION_URL }} >> .env
          echo GOOGLE_BOOKS_API=${{ secrets.GOOGLE_BOOKS_API }} >> .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          echo SEND_GRID_API=${{ secrets.SEND_GRID_API }} >> .env

      - name: Build the Docker test image
        run: docker-compose -f docker-compose.test.yml up --exit-code-from backend_test --build

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./app/coverage/clover.xml

      - name: Heroku Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "bibliotecadebolso"
          heroku_email: "diasrhenan@gmail.com"
          buildpack: "https://github.com/timanovsky/subdir-heroku-buildpack.git"
